version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: mainnet
        P2P_PORT: 9105
    environment:
      CHECKPOINT_SYNC_URL: "https://checkpoint-sync.dappnode.net"
    ports:
      - "9105:9105"
      - "9105:9105/udp"
    volumes:
      - teku-data:/opt/teku/data
  validator:
    build:
      args:
        NETWORK: mainnet
volumes:
  teku-data: {}
