version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: mainnet
        P2P_PORT: 9105
    ports:
      - "9105:9105/tcp"
      - "9105:9105/udp"
    volumes:
      - teku-data:/opt/teku/data
  validator:
    build:
      args:
        NETWORK: mainnet
volumes:
  teku-data: {}
