version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: gnosis
        P2P_PORT: 19005
    environment:
      CHECKPOINT_SYNC_URL: "https://checkpoint-sync-gnosis.dappnode.net"
    ports:
      - "19005:19005"
      - "19005:19005/udp"
    volumes:
      - teku-gnosis-data:/opt/teku/data
  validator:
    build:
      args:
        NETWORK: gnosis
volumes:
  teku-gnosis-data: {}
