version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: holesky
        P2P_PORT: 9605
    ports:
      - "9605:9605/tcp"
      - "9605:9605/udp"
    volumes:
      - teku-holesky-data:/opt/teku/data
  validator:
    build:
      args:
        NETWORK: holesky
        UPSTREAM_VERSION: develop # holesky fix, see https://github.com/ethereum/pm/blob/master/Pectra/holesky-postmortem.md#holesky-coordinated-slashings
volumes:
  teku-holesky-data: {}
