version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: hoodi
        P2P_PORT: 9705
    environment:
      CHECKPOINT_SYNC_URL: "https://checkpoint-sync-hoodi.dappnode.net"
    ports:
      - "9705:9705"
      - "9705:9705/udp"
  validator:
    build:
      args:
        NETWORK: hoodi
